- hosts: "{{ target }}"
  name: fbplay-win
  tasks:
    - name: Create dummy directory 1
      win_shell: "mkdir {{directory_name_1}}"
  tasks:
    - name: Create dummy directory 2
      win_shell: "mkdir {{directory_name_2}}"
