- hosts: "{{ target }}"
  name: fbplay-win
  tasks:
    - name: Create dummy directory 1
      win_shell: "mkdir {{directory_name_1}}"
    - name: Create dummy directory 2
      win_shell: "mkdir {{directory_name_2}}"
    - name: Create dummy file in directory
      win_file:
        path: "{{directory_name_1}}/{{file_name}}"
        state: touch
